"""Add task_id and session_type to StudySession

Revision ID: 09f1a6ae7bec
Revises: a90f576bf3f5
Create Date: 2025-10-28 15:49:00.182846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09f1a6ae7bec'
down_revision = '710cda667119'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop temporary table if it exists
    try:
        op.drop_table('_alembic_tmp_subjects')
    except:
        pass
        
    with op.batch_alter_table('study_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('session_type', sa.Enum('learn', 'practice', 'review', name='sessiontype'), nullable=False, server_default='learn'))
        batch_op.create_foreign_key('fk_study_sessions_task_id', 'tasks', ['task_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_sessions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_study_sessions_task_id', type_='foreignkey')
        batch_op.drop_column('session_type')
        batch_op.drop_column('task_id')

    # Recreate temp table if needed
    op.create_table('_alembic_tmp_subjects',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('workload', sa.INTEGER(), nullable=True),
    sa.Column('priority', sa.INTEGER(), nullable=True),
    sa.Column('difficulty', sa.INTEGER(), nullable=True),
    sa.Column('exam_date', sa.DATETIME(), nullable=True),
    sa.Column('color', sa.VARCHAR(length=7), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.CheckConstraint('difficulty >= 1 AND difficulty <= 5', name='check_difficulty_range'),
    sa.CheckConstraint('priority >= 1 AND priority <= 5', name='check_priority_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
