"""Add grace_minutes and MakeupQueue table

Revision ID: 50050b7892d8
Revises: 09f1a6ae7bec
Create Date: 2025-10-29 15:41:51.609486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50050b7892d8'
down_revision = '09f1a6ae7bec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grace_minutes', sa.Integer(), nullable=True, server_default='30'))

    # Create makeup_queue table if it doesn't exist
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if 'makeup_queue' not in inspector.get_table_names():
        op.create_table('makeup_queue',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('subject_id', sa.Integer(), nullable=False),
            sa.Column('minutes', sa.Integer(), nullable=False),
            sa.Column('expires_at', sa.Date(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('makeup_queue', schema=None) as batch_op:
            batch_op.create_index('idx_makeup_expires', ['expires_at'], unique=False)
            batch_op.create_index('idx_makeup_user_subject', ['user_id', 'subject_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop makeup_queue table
    with op.batch_alter_table('makeup_queue', schema=None) as batch_op:
        batch_op.drop_index('idx_makeup_user_subject')
        batch_op.drop_index('idx_makeup_expires')
    op.drop_table('makeup_queue')
    
    # Drop grace_minutes column
    with op.batch_alter_table('study_preferences', schema=None) as batch_op:
        batch_op.drop_column('grace_minutes')

    # ### end Alembic commands ###
