"""Add locked field to StudySession

Revision ID: 710cda667119
Revises: 50050b7892d8
Create Date: 2025-10-29 16:22:08.782956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '710cda667119'
down_revision = 'b852b46eeaff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locked', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_sessions', schema=None) as batch_op:
        batch_op.drop_column('locked')

    # ### end Alembic commands ###
