"""Add UserConstraint, ClassBlock tables, status enum, indexes, and CHECK constraints

Revision ID: a90f576bf3f5
Revises: 
Create Date: 2025-10-28 14:26:15.136465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a90f576bf3f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add status column to study_sessions with default value
    with op.batch_alter_table('study_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('planned', 'completed', 'missed', 'canceled', name='sessionstatus'), nullable=False, server_default='planned'))
        batch_op.create_index('idx_status', ['status'], unique=False)
        batch_op.create_index('idx_subject_id', ['subject_id'], unique=False)
        batch_op.create_index('idx_user_start_time', ['user_id', 'start_time'], unique=False)

    # Add index to tasks
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index('idx_user_subject', ['user_id', 'subject_id'], unique=False)
    
    # Add CHECK constraints to subjects (SQLite specific using batch mode)
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_check_constraint('check_priority_range', 'priority >= 1 AND priority <= 5')
        batch_op.create_check_constraint('check_difficulty_range', 'difficulty >= 1 AND difficulty <= 5')
    
    # Create UserConstraint table (if not exists via db.create_all)
    # Check if table exists first by using bind to get connection
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()
    
    if 'user_constraints' not in existing_tables:
        op.create_table(
            'user_constraints',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('title', sa.String(length=128), nullable=False),
            sa.Column('day_of_week', sa.Integer(), nullable=False),
            sa.Column('start_time', sa.Time(), nullable=False),
            sa.Column('end_time', sa.Time(), nullable=False),
            sa.Column('is_hard', sa.Boolean(), nullable=False, server_default='1'),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.CheckConstraint('day_of_week >= 0 AND day_of_week <= 6', name='check_day_range'),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index('idx_user_day', 'user_constraints', ['user_id', 'day_of_week'], unique=False)
    
    if 'class_blocks' not in existing_tables:
        # Create ClassBlock table
        op.create_table(
            'class_blocks',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('title', sa.String(length=128), nullable=False),
            sa.Column('day_of_week', sa.Integer(), nullable=False),
            sa.Column('start_time', sa.Time(), nullable=False),
            sa.Column('end_time', sa.Time(), nullable=False),
            sa.Column('location', sa.String(length=128), nullable=True),
            sa.Column('color', sa.String(length=7), nullable=True, server_default='#6c757d'),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.CheckConstraint('day_of_week >= 0 AND day_of_week <= 6', name='check_class_day_range'),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index('idx_class_user_day', 'class_blocks', ['user_id', 'day_of_week'], unique=False)
    
    # Migrate existing data: set status to 'completed' where completed=True
    op.execute("UPDATE study_sessions SET status = 'completed' WHERE completed = 1")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop new tables
    op.drop_index('idx_class_user_day', table_name='class_blocks')
    op.drop_table('class_blocks')
    op.drop_index('idx_user_day', table_name='user_constraints')
    op.drop_table('user_constraints')
    
    # Remove CHECK constraints from subjects
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_constraint('check_difficulty_range', type_='check')
        batch_op.drop_constraint('check_priority_range', type_='check')
    
    # Remove index from tasks
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('idx_user_subject')

    # Remove indexes and status column from study_sessions
    with op.batch_alter_table('study_sessions', schema=None) as batch_op:
        batch_op.drop_index('idx_user_start_time')
        batch_op.drop_index('idx_subject_id')
        batch_op.drop_index('idx_status')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
