"""Add actual_minutes and completed_at tracking fields

Revision ID: bdb66ade9f6b
Revises: 710cda667119
Create Date: 2025-10-29 16:34:26.741911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdb66ade9f6b'
down_revision = '710cda667119'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_sessions', schema=None) as batch_op:
        batch_op.drop_column('completed_at')
        batch_op.drop_column('actual_minutes')

    # ### end Alembic commands ###
